### ISSUE TITLE
Error in kangaroo_smat make

### ISSUE THREAD

**Issue by msuardi** [jisraeli/DeepBind#3]
When I try to make in kangaroo_smat, the first execution of nvcc raise an error:
nvcc	 -c -o ../build/release/obj/KANGAROO_SMAT/autotune.o -I. -I/usr/local/cuda/include -I../../smat/src  -DKANGAROO_SMAT_EXPORTS -use_fast_math -gencode arch=compute_50,code=sm_50 -include nvcc_preinclude.h -maxrregcount 64 -Xcompiler -m64,-fPIC,-fvisibility=hidden,--param,max-inline-recursive-depth=24,--param,max-inline-recursive-depth-auto=24,-O3, autotune.cu
/usr/local/cuda/include/cuda.h(60): error: "uint64_t" is ambiguous

1 error detected in the compilation of "/tmp/tmpxft_000020b5_00000000-7_autotune.cpp1.ii".
makefile:159: recipe for target '../build/release/obj/KANGAROO_SMAT/autotune.o' failed
make: *** [../build/release/obj/KANGAROO_SMAT/autotune.o] Error 2

What about it? I don't know where is the problem.
Thanks!
Mauro

**Comment by litao-csu** [comment]
I got the same issue. Did you resolved this problem?
Thanks!

**Comment by litao-csu** [comment]
@msuardi I got the same issue. Did you resolve this problem?
Thanks!

**Comment by samridhim** [comment]
i got the same issue. did it get resolved?

**Comment by mrendleman** [comment]
I also encountered this issue. I tried it with a variety of CUDA versions (8.0.44, 8.0.61, 9.0.176.1, 9.1.85.2, etc) but only managed to get it working with a CUDA 7 version, 7.0.28. There seem to be several issues in the code related to CUDA version ([issue #4](https://github.com/jisraeli/DeepBind/issues/4)) so I'd recommend using CUDA 7.

The risk with CUDA 7 though, seems to be [known issues](https://github.com/apache/incubator-mxnet/issues/4089) with cuda 7.0 and 7.5's random number generator on GPUs that use the pascal architecture.
